### ISSUE TITLE
Change behavior of "needs drawing"

### ISSUE THREAD

**Issue by mm-52tFd** [morops/deep-blue-parts#14]
Currently, needs drawing is a status. There is a checkbox for "drawing created" that has an associated database entry.

Remove "needs drawing" status from user display. Remove "drawing created" and toggle that based on whether one has been uploaded. The "needs drawing" status should be updated automatically based off of the above method.

**Comment by icecube45** [comment]
Drawing created is now set upon drawing upload
However the "needs drawing" status has not been changed as of now - we should powwow about this as I'm unsure how to implement unless we're considering reducing possible statuses to a total of like.. 3

**Comment by mm-52tFd** [comment]
In part overview, change "no" entry under needs drawing to the needs drawing badge (for pretty colors).

Remove needs drawing as a status. Change dashboard behavior so that we can still select by parts that need a drawing.

**Comment by icecube45** [comment]
Dashboard remains and status removed in permissions_overhaul (i forgot to change branches and im too tired to fix git)
