### ISSUE TITLE
Fix documentation overwrite bug

### ISSUE THREAD

**Issue by mm-52tFd** [morops/deep-blue-parts#16]
Uploading new documentation does not overwrite old documentation file

**Comment by mm-52tFd** [comment]
issue is likely to affect toolpaths as well

**Comment by mm-52tFd** [comment]
If a part is reset to an earlier revision, check behavior. For example, if we reset from C->B, a new upload is rev C again, but that file will already exist.

**Comment by icecube45** [comment]
Fixed in parts_upload
