### ISSUE TITLE
Add file upload

### ISSUE THREAD

**Issue by mm-52tFd** [morops/deep-blue-parts#4]
Add file upload to parts and assemblies, specifically

- drawing (PDF)
- documentation (PDF)
- Toolpath (gcode)

1.  Uploaded files shall be stored in a directory structure
Organization should be similar to the following:
`[PART ID]`
`|----drawing`
`\----[PART_ID]_[VERSION].PDF`
`|----docs`
`\----[PART_ID]_docs.PDF`
`|----toolpath`
`\----[PART_ID].gcode`

2. "Version control" shall be implemented for drawing uploads.
- A current revision latter shall be stored as a part instance variable. The letter is incremented every time a new drawing (and only drawing) is uploaded. If we use 26 versions:
-- Smack the CAD team
-- Roll over to AA, AB, etc

- The rev letter shall be displayed in the part info page
- The rev letter may be reset to a previous version by an admin, which changes the drawing that the part page points to or renders

3. Uploads shall be capped at 5MB.

4. Access to viewing uploaded files shall be restricted to users who are signed in

5. When a part is deleted, recursively delete the associated directory.

**Comment by icecube45** [comment]
State of the union for part_uploads branch:

- File upload and associated directory management is workings

- PDFs and Links will show if they exist and dependent on has drawing checkbox, they need styling

- Version control currently increments and saves old files, but no way to "revert" yet
- Uploads are size restricted and type restricted with client side validation

**Comment by mm-52tFd** [comment]
Added revert to previous revision letter. Reverting does not delete "future" versions that were previously stored in case the value is changed accidentally. There is no way to revert back to a previous version, perhaps we should add that. We could do it fairly easily by using an array to keep track of what revs have been entered, and this way @part.rev is just a pointer to the intended proper revision without actually affecting anything.

Now that I typed this out, it makes a lot of sense. I'll go ahead and add that tomorrow.

**Comment by icecube45** [comment]
@morops I've restricted revision control to administrators - perhaps we need a new permission for this

**Comment by mm-52tFd** [comment]
I think we need some new classes of users as well. Currently we have admin, edit, and read only. I would like to add design as a special class of user editing with a little more access than general edit, which would be presumably for shop students.

**Comment by icecube45** [comment]
That's more of less what I meant by new permission, but I'm agreed with you
