### ISSUE TITLE
Update part numbering function to match 199 spec, or change 199 spec to match numbering function

### ISSUE THREAD

**Issue by mm-52tFd** [morops/deep-blue-parts#6]

**Comment by icecube45** [comment]
@morops can you provide more detail on the 199 spec?

**Comment by mm-52tFd** [comment]
See part naming convention under Design/Standards on drive. Likely to just use the 254 system, since the 199 system was assuming manual entry originally and so we decided to not do things like group parts by parent assembly.

**Comment by mm-52tFd** [comment]
updating 199 convention to match 254
